export const candidatesConstants = {
  GET_ALL_CANDIDATES_REQUEST: "GET_ALL_CANDIDATES_REQUEST",
  GET_ALL_CANDIDATES_SUCCESS: "GET_ALL_CANDIDATES_SUCCESS",
  GET_ALL_CANDIDATES_FAILURE: "GET_ALL_CANDIDATES_FAILURE",
};
