export const candidatesConstants = {
  POST_CANDIDATE_REQUEST: "POST_CANDIDATE_REQUEST",
  POST_CANDIDATE_SUCCESS: "POST_CANDIDATE_SUCCESS",
  POST_CANDIDATE_FAILURE: "POST_CANDIDATE_FAILURE",
  GET_ALL_CANDIDATES_REQUEST: "GET_ALL_CANDIDATES_REQUEST",
  GET_ALL_CANDIDATES_SUCCESS: "GET_ALL_CANDIDATES_SUCCESS",
  GET_ALL_CANDIDATES_FAILURE: "GET_ALL_CANDIDATES_FAILURE",
  UPDATE_CANDIDATE_REQUEST: "UPDATE_CANDIDATE_REQUEST",
  UPDATE_CANDIDATE_SUCCESS: "UPDATE_CANDIDATE_SUCCESS",
  UPDATE_CANDIDATE_FAILURE: "UPDATE_CANDIDATE_FAILURE",
};
