export const inscriptoConstants = {
    POST_NUEVOINSCRIPTO_REQUEST: 'POST_NUEVOINSCRIPTO_REQUEST',
    POST_NUEVOINSCRIPTO_SUCCESS: 'POST_NUEVOINSCRIPTO_SUCCESS',
    POST_NUEVOINSCRIPTO_FAILURE: 'POST_NUEVOINSCRIPTO_FAILURE',
    SAVE_TO_PRINT: 'SAVE_TO_PRINT'
}